name: "pre-release"

on: workflow_dispatch

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "macos-13"

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'rdkit/rdkit'
          ref: 'Release_2022_09'
      - name: "Build"
        run: |
          find . -type f >file1
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            file1
